import { scoreLeadOpportunity } from "@/lib/leadgen/scoring";
import type { LeadOpportunity, LeadOpportunitySeed } from "@/lib/leadgen/types";

const now = new Date().toISOString();

const baseSeeds: LeadOpportunitySeed[] = [
  {
    id: "opp-1",
    businessName: "Bayview Dental Studio",
    category: "Dental",
    city: "San Jose",
    state: "CA",
    phone: "(408) 555-1201",
    email: "info@bayviewdental.example",
    website: null,
    googleProfileUrl: "https://maps.google.com/?cid=bayviewdental",
    address: "100 First St",
    rating: 3.9,
    reviewCount: 8,
    hasWebsite: false,
    hasGoogleBusinessProfile: true,
    hasBookingLink: false,
    hasContactForm: false,
    hasSocialLinks: false,
    websiteQuality: "none",
    responseSpeedSignal: "slow",
    source: "mock_local",
    sourceUrl: null,
    status: "discovered",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "opp-2",
    businessName: "PrimeFlow Plumbing",
    category: "Plumbing",
    city: "Oakland",
    state: "CA",
    phone: "(510) 555-1911",
    email: null,
    website: "https://primeflow.example",
    googleProfileUrl: null,
    address: "900 Grand Ave",
    rating: 4.1,
    reviewCount: 12,
    hasWebsite: true,
    hasGoogleBusinessProfile: false,
    hasBookingLink: false,
    hasContactForm: false,
    hasSocialLinks: true,
    websiteQuality: "weak",
    responseSpeedSignal: "average",
    source: "mock_local",
    sourceUrl: null,
    status: "reviewed",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "opp-3",
    businessName: "Elite RoofWorks",
    category: "Roofing",
    city: "Fremont",
    state: "CA",
    phone: "(510) 555-2222",
    email: "ops@eliteroofworks.example",
    website: "https://eliteroofworks.example",
    googleProfileUrl: "https://maps.google.com/?cid=eliteroofworks",
    address: "44 Blacow Rd",
    rating: 4.6,
    reviewCount: 49,
    hasWebsite: true,
    hasGoogleBusinessProfile: true,
    hasBookingLink: false,
    hasContactForm: true,
    hasSocialLinks: true,
    websiteQuality: "average",
    responseSpeedSignal: "average",
    source: "domain_list",
    sourceUrl: "https://example-list.local/roofing.csv",
    status: "discovered",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "opp-4",
    businessName: "Urban Chill HVAC",
    category: "HVAC",
    city: "San Francisco",
    state: "CA",
    phone: "(415) 555-8800",
    email: "hello@urbanchill.example",
    website: "https://urbanchill.example",
    googleProfileUrl: null,
    address: "75 Mission St",
    rating: 3.7,
    reviewCount: 6,
    hasWebsite: true,
    hasGoogleBusinessProfile: false,
    hasBookingLink: false,
    hasContactForm: false,
    hasSocialLinks: false,
    websiteQuality: "weak",
    responseSpeedSignal: "slow",
    source: "manual_csv",
    sourceUrl: null,
    status: "discovered",
    createdAt: now,
    updatedAt: now,
  },
];

export function getMockLeadOpportunities(): LeadOpportunity[] {
  return baseSeeds.map(scoreLeadOpportunity);
}
